### ISSUE TITLE
android:tint does not exist for <shape> at API Level 21

### ISSUE THREAD

**Issue by john2020star** [devgianlu/CommonUtils#42]
I found that you have specified the attribute android:tint in <shape>, which only exists starting from API level 22. You have specified it in shadow_bottom.xml, shadow_start.xml and shadow_top.xml, avoid using it.

**Comment by devgianlu** [comment]
Not sure what you mean, `android:tint` has been added in API 21. [Reference](https://developer.android.com/reference/android/graphics/drawable/Drawable#setTint(int))

**Comment by john2020star** [comment]
Yes, it is actually a bug in the Android framework. Check this link for your reference. https://github.com/zhanghai/AndroidFastScroll/commit/91a796aa72411d01768fa3526aca6163ed1e8e57

Workaround by using the API setTintList instead of the attribute.
